<a href="https://colab.research.google.com/github/ADinng/CS6405_Datamining/blob/main/CS6405_Datamining_lecturenotes1_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# L02 - pandas

In [ ]:
import pandas as pd

data = {
    'state': ['Ohio', 'Ohio','Nevada','Nevada'],
    'year':[2000, 2001, 2003, 2003],
    'pop':[1.5, 1.7, 3.6, 2.4]
}

frame = pd.DataFrame(data)
print(frame)


    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2  Nevada  2003  3.6
3  Nevada  2003  2.4


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/andvise/DataAnalyticsDatasets/refs/heads/main/vgsales.csv?row=True')

In [ ]:
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [ ]:
print(df.shape)
print(df.dtypes)

(16598, 11)
Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object


In [ ]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [ ]:
df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [ ]:
df.shape[0]*df.shape[1]

182578

In [ ]:
df.size

182578

In [ ]:
df.info

<bound method DataFrame.info of         Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]>

# L3-preprocessing in pandas

In [ ]:
df['Name']

0                                              Wii Sports
1                                       Super Mario Bros.
2                                          Mario Kart Wii
3                                       Wii Sports Resort
4                                Pokemon Red/Pokemon Blue
                               ...                       
16593                  Woody Woodpecker in Crazy Castle 5
16594                       Men in Black II: Alien Escape
16595    SCORE International Baja 1000: The Official Game
16596                                          Know How 2
16597                                    Spirits & Spells
Name: Name, Length: 16598, dtype: object

In [ ]:
df.Name

0                                              Wii Sports
1                                       Super Mario Bros.
2                                          Mario Kart Wii
3                                       Wii Sports Resort
4                                Pokemon Red/Pokemon Blue
                               ...                       
16593                  Woody Woodpecker in Crazy Castle 5
16594                       Men in Black II: Alien Escape
16595    SCORE International Baja 1000: The Official Game
16596                                          Know How 2
16597                                    Spirits & Spells
Name: Name, Length: 16598, dtype: object

In [ ]:
df.head(2)

Rank               Name Platform    Year     Genre Publisher  NA_Sales  \
0     1         Wii Sports      Wii  2006.0    Sports  Nintendo     41.49   
1     2  Super Mario Bros.      NES  1985.0  Platform  Nintendo     29.08   

   EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     29.02      3.77         8.46         82.74  
1      3.58      6.81         0.77         40.24

In [ ]:
df.tail(3)

Rank                                              Name Platform  \
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year     Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
16595  2008.0    Racing  Activision      0.00      0.00       0.0   
16596  2010.0    Puzzle    7G//AMES      0.00      0.01       0.0   
16597  2003.0  Platform     Wanadoo      0.01      0.00       0.0   

       Other_Sales  Global_Sales  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01

In [ ]:
df.describe()

Rank          Year      NA_Sales      EU_Sales      JP_Sales  \
count  16598.000000  16327.000000  16598.000000  16598.000000  16598.000000   
mean    8300.605254   2006.406443      0.264667      0.146652      0.077782   
std     4791.853933      5.828981      0.816683      0.505351      0.309291   
min        1.000000   1980.000000      0.000000      0.000000      0.000000   
25%     4151.250000   2003.000000      0.000000      0.000000      0.000000   
50%     8300.500000   2007.000000      0.080000      0.020000      0.000000   
75%    12449.750000   2010.000000      0.240000      0.110000      0.040000   
max    16600.000000   2020.000000     41.490000     29.020000     10.220000   

        Other_Sales  Global_Sales  
count  16598.000000  16598.000000  
mean       0.048063      0.537441  
std        0.188588      1.555028  
min        0.000000      0.010000  
25%        0.000000      0.060000  
50%        0.010000      0.170000  
75%        0.040000      0.470000  
max       10.570000     82.740000

In [ ]:
df.Global_Sales.max()

82.74

In [ ]:
df.Global_Sales.min()

0.01

In [ ]:
# hand missing value

import pandas as pd
from numpy import nan as NA

data = pd.DataFrame([[1, 6.5, 3], [1, NA, NA], [NA, NA, NA], [NA, 6.5, 3]])

In [ ]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
# remove all rows at least a NaN
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [ ]:
cleaned = data.dropna(how = "all")
cleaned

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
# add new column
data[4]=NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [ ]:
# remove all columns with only NaN
cleaned = data.dropna(axis=1, how="all")
cleaned

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
# fill NaN with a value
data = data.fillna(0)
data

0    1    2    4
0  1.0  6.5  3.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  6.5  3.0  0.0

In [ ]:
data[4]

0    0.0
1    0.0
2    0.0
3    0.0
Name: 4, dtype: float64

In [ ]:
manga = {"One Pice": {2011: 8.4, 2012: 9.9, 2013: 11.3},
         "One-Punch Man":{2012: 2.3, 2013: 2.7},
         "Berserk":{2011: 2.7, 2012: 2.1, 2013: 1.8}}
df = pd.DataFrame(manga)
df

One Pice  One-Punch Man  Berserk
2011       8.4            NaN      2.7
2012       9.9            2.3      2.1
2013      11.3            2.7      1.8

In [ ]:
df["Berserk"]

2011    2.7
2012    2.1
2013    1.8
Name: Berserk, dtype: float64

In [ ]:
df.Berserk

2011    2.7
2012    2.1
2013    1.8
Name: Berserk, dtype: float64

In [ ]:
df[["Berserk", "One Pice"]]

Berserk  One Pice
2011      2.7       8.4
2012      2.1       9.9
2013      1.8      11.3

In [ ]:
df[0:2]

One Pice  One-Punch Man  Berserk
2011       8.4            NaN      2.7
2012       9.9            2.3      2.1

In [ ]:
df.loc[0:1, "One Pice"]

Series([], Name: One Pice, dtype: float64)

In [ ]:
df.loc[2011, "Berserk"]

2.7

In [ ]:
df.loc[2011:2012, "One Pice":"Berserk"]

One Pice  One-Punch Man  Berserk
2011       8.4            NaN      2.7
2012       9.9            2.3      2.1

In [ ]:
df.loc[[2011, 2013], ["One Pice","Berserk"]]

One Pice  Berserk
2011       8.4      2.7
2013      11.3      1.8

In [ ]:
df.iloc[1,2]

2.1

In [ ]:
df.iloc[:2, 0:3]

One Pice  One-Punch Man  Berserk
2011       8.4            NaN      2.7
2012       9.9            2.3      2.1

In [ ]:
df.iloc[[0,2],[0,2]]

One Pice  Berserk
2011       8.4      2.7
2013      11.3      1.8

In [ ]:
df["One Pice"] = [9, 10, 11]

In [ ]:
df["Naruto"] = [9, 10, 11]

In [ ]:
df["Apple"] = df["Naruto"]-1

In [ ]:
df = df[["One Pice", "Berserk"]]

In [ ]:
df.loc[2011]=[9, 3]

In [ ]:
df.loc[2014]=[10, 8]

<ipython-input-73-852f60e833a5>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[2014]=[10, 8]


In [ ]:
df.loc[2015]=df.loc[2013]*2

<ipython-input-75-83ddb9c95f97>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[2015]=df.loc[2013]*2


In [ ]:
df

One Pice  Berserk
2011       9.0      3.0
2012      10.0      2.1
2013      11.0      1.8
2014      10.0      8.0
2015      22.0      3.6

In [ ]:
df_Berserk = df.groupby('Berserk')

In [ ]:
df_Berserk

In [ ]:
df_Berserk.mean()

One Pice  One-Punch Man
Berserk                         
1.8          11.3            2.7
2.1           9.9            2.3
2.7           8.4            NaN

In [ ]:
df.groupby('Berserk')['One Pice'].min()

Berserk
1.8    11.3
2.1     9.9
2.7     8.4
Name: One Pice, dtype: float64

In [ ]:
df_sorted = df.sort_values(by="Berserk", ascending=False)
df_sorted

One Pice  One-Punch Man  Berserk
2011       8.4            NaN      2.7
2012       9.9            2.3      2.1
2013      11.3            2.7      1.8

In [ ]:
df_sorted = df.sort_values(by=["Berserk", "One Pice"], ascending=[True, False])
df_sorted

One Pice  One-Punch Man  Berserk
2011       8.4            NaN      2.7
2012       9.9            2.3      2.1
2013      11.3            2.7      1.8

In [ ]:
df[["Berserk", "One Pice"]].agg(['min','mean','max'])

Berserk   One Pice
min       1.8   8.400000
mean      2.2   9.866667
max       2.7  11.300000

In [ ]:
df.groupby('Berserk')['One Pice'].agg(['max', 'mean'])

max  mean
Berserk            
1.8      11.3  11.3
2.1       9.9   9.9
2.7       8.4   8.4

# L567-KNN

min-max scaling

In [ ]:
from sklearn import preprocessing
import numpy as np
customer = np.array([[35, 35, 3],[22, 50, 2],[63, 200, 1], [59, 170, 1], [25, 40, 4]])
print(customer)

[[ 35  35   3]
 [ 22  50   2]
 [ 63 200   1]
 [ 59 170   1]
 [ 25  40   4]]


In [ ]:
scalingObj = preprocessing.MinMaxScaler()
new_customer = scalingObj.fit_transform(customer)
print(new_customer)

[[0.31707317 0.         0.66666667]
 [0.         0.09090909 0.33333333]
 [1.         1.         0.        ]
 [0.90243902 0.81818182 0.        ]
 [0.07317073 0.03030303 1.        ]]


In [ ]:
david = np.array([[37, 50, 2]])
new_david = scalingObj.transform(david)
new_david

array([[0.36585366, 0.09090909, 0.33333333]])

In [ ]:
scalingObj.data_max_

array([ 63., 200.,   4.])

In [ ]:
scalingObj.data_min_

array([22., 35.,  1.])

standardizing data

In [ ]:
standscaling = preprocessing.StandardScaler()
st_customer = standscaling.fit_transform(customer)
print(st_customer)

[[-0.33932637 -0.90114035  0.68599434]
 [-1.09988549 -0.68993558 -0.17149859]
 [ 1.29880095  1.42211211 -1.02899151]
 [ 1.06478276  0.99970257 -1.02899151]
 [-0.92437184 -0.83073876  1.54348727]]


In [ ]:
st_david = standscaling.transform(david)
st_david

array([[-0.22231728, -0.68993558, -0.17149859]])

In [ ]:
standscaling.mean_

array([40.8, 99. ,  2.2])

In [ ]:
standscaling.var_

array([2.9216e+02, 5.0440e+03, 1.3600e+00])

# L10and11-Scikit-learn

In [ ]:
from sklearn import datasets
from sklearn import neighbors


iris = datasets.load_iris()

knn = neighbors.KNeighborsClassifier(n_neighbors = 5)
knn.fit(iris.data, iris.target)
print(knn.predict([[3, 5, 4, 2]]))

[1]


In [ ]:
import pandas as pd
from sklearn import neighbors
from sklearn import metrics
from sklearn import model_selection
import matplotlib.pyplot as plt

df = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header = None)
df.columns = ["Class", "Alcohol", "Malic acid", "Ash" , "Alcalinity of ash", "Magnesium", "Total phenols", "Flavanoids", "Nonflavanoid phenols", "Proanthocyanins", "Color intensity", "Hue", "OD280/OD315 of diluted wines", "Proline"]

features = df.loc[:, "Alcohol": "Proline"]
labels = df["Class"]

train_features, test_features, train_labels, test_labels = model_selection.train_test_split(features, labels, test_size = 0.2, random_state = 0)

# grid search
knn = neighbors.KNeighborsClassifier()
parameters = {'n_neighbors':[1, 3, 5, 7, 11]}

clf = model_selection.GridSearchCV(knn, parameters)
clf.fit(train_features, train_labels)

print("The best classifier is:", clf.best_estimator_)
print("The accuracy is: ", clf.best_score_)
print("Its parameters are:", clf.best_params_)


The best classifier is: KNeighborsClassifier(n_neighbors=1)
The accuracy is:  0.7746305418719212
Its parameters are: {'n_neighbors': 1}


In [ ]:
from sklearn import tree

dtc = tree.DecisionTreeClassifier()
parameters = {'criterion':["entropy", "gini"],'max_depth':[2, 3, 4], 'min_impurity_decrease':[0.01, 0.1, 0.2]}

clf = model_selection.GridSearchCV(dtc, parameters, cv=10)
clf.fit(train_features, train_labels)

print("The best classifier is:", clf.best_estimator_)
print("The accuracy is: ", clf.best_score_)
print("Its parameters are:", clf.best_params_)

clf.best_estimator_.score(test_features, test_labels)

The best classifier is: DecisionTreeClassifier(max_depth=4, min_impurity_decrease=0.01)
The accuracy is:  0.9376190476190477
Its parameters are: {'criterion': 'gini', 'max_depth': 4, 'min_impurity_decrease': 0.01}


0.9722222222222222

In [ ]:
train_features.shape

(142, 13)

In [ ]:
train_labels.shape

(36, 13)

# L13-Encoding and Bow

In [ ]:
import pandas as pd
seriesA = pd.Series(['A', 'C','B'])
seriesB = pd.Series([21, 18, 19])
seriesC = pd.Series([4, 1, 1])
seriesD = pd.Series(['Computing', 'Biology','Chemistry'])

df = pd.DataFrame({'Grade': seriesA, 'Age': seriesB, 'DegreeYear':seriesC, 'Department': seriesD})


grade_mapping = {'F':0, 'D':1, 'C':2, 'B':3, 'A':4}
df['Grade'] = df['Grade'].map(grade_mapping)


from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
df['Department'] = class_le.fit_transform(df['Department'].values)
print(df)

   Grade  Age  DegreeYear  Department
0      4   21           4           2
1      2   18           1           0
2      3   19           1           1


In [ ]:
df = pd.get_dummies(df, columns = ["Department"])
print(df)

   Grade  Age  DegreeYear  Department_0  Department_1  Department_2
0      4   21           4         False         False          True
1      2   18           1          True         False         False
2      3   19           1         False          True         False


In [ ]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
tweets = [
"No one is born hating another person because of the color of his skin or his background or his religion.",
"People must learn to hate, and if they can learn to hate, they can be taught to love.",
"For love comes more naturally to the human heart than its opposite."
]

# create the vectorizer

vectorizer = CountVectorizer(stop_words = 'english')

# run the vectorizer
vectorizer.fit(tweets)
X = vectorizer.transform(tweets)
print(X)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 18 stored elements and shape (3, 17)>
  Coords	Values
  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 5)	1
  (0, 13)	1
  (0, 14)	1
  (0, 15)	1
  (1, 4)	2
  (1, 8)	2
  (1, 9)	1
  (1, 12)	1
  (1, 16)	1
  (2, 3)	1
  (2, 6)	1
  (2, 7)	1
  (2, 9)	1
  (2, 10)	1
  (2, 11)	1


In [ ]:
vectorizer.get_feature_names_out()

array(['background', 'born', 'color', 'comes', 'hate', 'hating', 'heart',
       'human', 'learn', 'love', 'naturally', 'opposite', 'people',
       'person', 'religion', 'skin', 'taught'], dtype=object)

In [ ]:
new_document = "Unsurprisingly, people hate to learn that their religion loves to hate"

new_document_as_vector = vectorizer.transform([new_document])

print(new_document_as_vector)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (1, 17)>
  Coords	Values
  (0, 4)	2
  (0, 8)	1
  (0, 12)	1
  (0, 14)	1


# L14 - PCA

In [ ]:
from sklearn import neighbors
from sklearn import metrics
from sklearn import model_selection
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.datasets import load_breast_cancer


data = load_breast_cancer()
train_features, test_features, train_labels, test_labels = model_selection.train_test_split(data.data, data.target, test_size=0.2, random_state=10)

scaler = MinMaxScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)
print("Training set size ", train_features.shape)

pca = PCA(n_components=4)
train_features = pca.fit_transform(train_features)
test_features = pca.transform(test_features)
print("Training set size after PCA", train_features.shape)


knn = neighbors.KNeighborsClassifier()
parameters = {'n_neighbors': [1, 3, 5, 7, 11]}
clf = model_selection.GridSearchCV(knn, parameters)
clf.fit( train_features, train_labels)
print("The best classifier is:", clf.best_estimator_)
print("Its accuracy is:",clf.best_score_)
print("Its parameters are:",clf.best_params_)

Training set size  (455, 30)
Training set size after PCA (455, 4)
The best classifier is: KNeighborsClassifier(n_neighbors=7)
Its accuracy is: 0.9626373626373625
Its parameters are: {'n_neighbors': 7}


In [ ]:
from sklearn import neighbors
from sklearn import metrics
from sklearn import model_selection
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.datasets import load_breast_cancer
from sklearn.pipeline import Pipeline

data = load_breast_cancer()
train_features, test_features, train_labels, test_labels = model_selection.train_test_split(data.data, data.target, test_size=0.2, random_state=10)

pipe_lr = Pipeline([('scl', MinMaxScaler()), ('dr', PCA(8)), ('clf',neighbors.KNeighborsClassifier(5))])


pipe_lr.fit(train_features, train_labels)

predictedResults = pipe_lr.predict(test_features)
print(metrics.accuracy_score(predictedResults, test_labels))
# Alternatively we could substitute this line (instead of the last two lines)
print('Test Accuracy:', pipe_lr.score(test_features, test_labels))



#using pipelines for cross fold validation
from sklearn.model_selection import cross_val_score
results = cross_val_score(pipe_lr, train_features, train_labels, cv=10)
print(results.mean())



0.9824561403508771
Test Accuracy: 0.9824561403508771
0.9581642512077295
