<a href="https://colab.research.google.com/github/ADinng/CS6405_Datamining/blob/main/CS6405_Datamining_L05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = np.array([[10], [20], [30], [40], [50]])
scaler = MinMaxScaler(feature_range=(0, 1))  # Scale between 0 and 1
normalized_data = scaler.fit_transform(data)
print(normalized_data)


[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [ ]:
from sklearn import preprocessing
import numpy as np

customer = np.array([[35, 35, 3],
                     [22, 50, 2],
                     [63, 200, 1],
                     [59, 170, 1],
                     [25, 40, 4]]
                    )

print(customer)
print("=================")

# Define and fit the scaler
scalingObj = preprocessing.StandardScaler()  # or preprocessing.MinMaxScaler()
scalingObj.fit(customer)  # Fit the scaler to the data

# Transform the data
new_customer = scalingObj.transform(customer)
print(new_customer)

[[ 35  35   3]
 [ 22  50   2]
 [ 63 200   1]
 [ 59 170   1]
 [ 25  40   4]]
[[-0.33932637 -0.90114035  0.68599434]
 [-1.09988549 -0.68993558 -0.17149859]
 [ 1.29880095  1.42211211 -1.02899151]
 [ 1.06478276  0.99970257 -1.02899151]
 [-0.92437184 -0.83073876  1.54348727]]


In [ ]:
#  let's
import pandas as pd
np.random.seed(2021)
seriesA = pd.Series(np.random.rand(4)*100, index=['a','b','c','d'])


